version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
