steps:
  - label: "RSpec :rspec:"
    command: bundle exec rspec
    artifact_paths: "log/rspec-*.xml"
    key: "rspec"
    env:
      RAILS_ENV: test
    plugins:
      - docker-compose#v3.0.0:
          run: app
          env:
            - BUILDKITE_JOB_ID
            - CI
            - RAILS_ENV

  - label: Test Summary
    depends_on: "rspec"
    plugins:
      - bugcrowd/test-summary#v1.9.0:
          inputs:
            - label: "RSpec :rspec:"
              artifact_path: "log/rspec*"
              type: junit
          formatter:
            type: details
          context: test-summary
