steps:
  - label: "RSpec :rspec:"
    command: bundle exec rspec
    artifact_paths: "log/rspec-*.xml"
    key: "rspec"
    env:
      RAILS_ENV: test
    plugins:
      - docker-compose#v3.0.0:
          run: app
          env:
            - BUILDKITE_JOB_ID
            - CI
            - RAILS_ENV

  - label: Test Summary
    depends_on: "rspec"
    plugins:
      - bugcrowd/test-summary#v1.9.0:
          inputs:
            - label: "RSpec :rspec:"
              artifact_path: "log/rspec*"
              type: junit
          formatter:
            type: details
          context: test-summary

  # For master builds only 👇

  - name: "📦"
    key: "build"
    command: ".buildkite/build.sh"
    branches: "master"
    artifact_paths: "dist/*"
    plugins:
      - docker-compose#ed68516f132338342cd3a85098be65f019136e4c:
          run: app

  - name: ":docker: push"
    command: ".buildkite/push-image.sh"
    depends_on: "build"
    branches: "master"
    agents:
      queue: deploy-production
    plugins:
      ecr#v2.0.0:
        login: true
        account-ids: ${ECR_ACCOUNT_ID}
