steps:
  - label: ":rspec: RSpec"
    command: bundle exec rspec
    artifact_paths: "log/rspec-*.xml"
    key: "rspec"
    env:
      RAILS_ENV: test
    plugins:
      - docker-compose#v3.0.0:
          run: app
          env:
            - BUILDKITE_JOB_ID
            - CI
            - RAILS_ENV

  - label: ":junit: Test Summary"
    depends_on: "rspec"
    plugins:
      - bugcrowd/test-summary#v1.9.0:
          inputs:
            - label: ":rspec: RSpec"
              artifact_path: "log/rspec*"
              type: junit
          formatter:
            type: details
          context: test-summary
  - label: ":lint-roller: Linting"
    commands:
      - curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s v2.2.2
      - ./bin/vale pages
  - label: ":lint-roller: Linting for insensitive words"
    commands:
      - wget https://nodejs.org/dist/v12.18.1/node-v12.18.1-linux-x64.tar.xz
      - mkdir -p /usr/local/lib/nodejs
      - tar -xJvf node-12.18.1-linux-x64.tar.xz -C /usr/local/lib/nodejs
      - export PATH=/usr/local/lib/nodejs/node-node-12.18.1-linux-x64/bin:$PATH
      - npm install
      - alex --diff pages/**/*.erb pages/**/*.txt
